config/routes.rb
Rails.application.routes.draw do
  
  resources :prohibitions
  resources :repertories
  resources :inscriptions do
    resources :appearers
  end

  resources :consultations


  devise_for :users
  authenticated :user do
    root 'welcome#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root "welcome#unregistered", as: :unregistered_root
    end
  end


end

app/models/repertory.rb
class Repertory < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :user, :num_repertory, :last_name, :name, :document, :inscription, :time_repertory, :date_repertory, :register, :num_inscription

end

app/controllers/repertories_controller.rb
class RepertoriesController < ApplicationController
  before_action :set_repertory, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /repertories
  # GET /repertories.json
  def index
    @repertories = Repertory.all
  end

  # GET /repertories/1
  # GET /repertories/1.json
  def show
  end

  # GET /repertories/new
  def new
    @repertory = Repertory.new
  end

  # GET /repertories/1/edit
  def edit
  end

  # POST /repertories
  # POST /repertories.json
  def create
    @repertory = current_user.repertories.new(repertory_params)

    respond_to do |format|
      if @repertory.save
        format.html { redirect_to @repertory, notice: 'Repertory was successfully created.' }
        format.json { render :show, status: :created, location: @repertory }
      else
        format.html { render :new }
        format.json { render json: @repertory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repertories/1
  # PATCH/PUT /repertories/1.json
  def update
    respond_to do |format|
      if @repertory.update(repertory_params)
        format.html { redirect_to @repertory, notice: 'Repertory was successfully updated.' }
        format.json { render :show, status: :ok, location: @repertory }
      else
        format.html { render :edit }
        format.json { render json: @repertory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repertories/1
  # DELETE /repertories/1.json
  def destroy
    @repertory.destroy
    respond_to do |format|
      format.html { redirect_to repertories_url, notice: 'Repertory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repertory
      @repertory = Repertory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repertory_params
      params.require(:repertory).permit(:user_id, :num_repertory, :last_name, :name, :document, :inscription, :time_repertory, :date_repertory, :register, :num_inscription)
    end
end

app/helpers/repertories_helper.rb
module RepertoriesHelper
end

app/views/repertories/_form.html.haml
.container.signup-box
  .row
    .col.s12.l12
      = simple_form_for(@repertory) do |f|
        -if @repertory.errors.any?
          #error_explanation
            %h3.chip
              = "#{@repertory.errors.count} errores encontrados:"
              <i class="material-icons">close</i>
            %ul
              -@repertory.errors.full_messages.each do |msg|
                %li.chip.waves-effect.waves-light.btn-large
                  =msg
                  <i class="material-icons">close</i>

        .row
          .col.s12.l12
            .section
              .row
                .col.s12.l12
                  .input-field.col.s6
                    %label{for: "#{:time_repertory}"} Hora de Ins.
                    %br
                    -if @repertory.time_repertory
                      = f.text_field :time_repertory, type: "time", value: "#{@repertory.time_repertory.strftime('%H:%M')}"
                    -else
                      = f.text_field :time_repertory, type: "time"
                  .input-field.col.s6
                    %label{for: "#{:date_repertory}"} Fecha de Ins.
                    %br
                    = f.text_field :date_repertory, type: "date", class: "datepicker"
              .row
                .col.s12.l12
                  .input-field.col.s6
                    = f.text_field :num_repertory
                    %label{for: "#{:num_repertory}", class: "active"} N° de Repertorio
                  .input-field.col.s6
                    = f.text_field :num_inscription
                    %label{for: "#{:num_inscription}", class: "active"} N° que Corresponde
              .row
                .col.s12.l12
                  .input-field.col.s12
                    = f.text_field :document
                    %label{for: "#{:document}", class: "active"} Naturaleza del Documento
                  .input-field.col.s12
                    = f.text_field :inscription
                    %label{for: "#{:inscription}", class: "active"} Clase de Inscripción
                  .input-field.col.s12
                    = f.text_field :register
                    %label{for: "#{:register}", class: "active"} Registro Parcial
              .row
                .col.s12.l12
                  .input-field.col.s6
                    = f.text_field :last_name
                    %label{for: "#{:last_name}", class: "active"} Apellidos
                  .input-field.col.s6
                    = f.text_field :name
                    %label{for: "#{:name}", class: "active"} Nombres
              .row
                .col.s6
                  %button{class:"btn btn-fb", type:"submit", name:"action"}
                    Guardar<i class="material-icons right">send</i>
                .col.s6
                  =link_to "Cancelar", repertories_path, class: "btn btn-fb"

app/views/repertories/edit.html.haml
=render "layouts/navbar"
.container.grey.lighten-3
  .row
    .col.s12.l12
      .row
        .col.s12.l12
          %h4.center-align Editar Repertorio
      .row
        .col.s12.l12
          = render 'form'

=render "layouts/footer"

app/views/repertories/index.html.haml
=render "layouts/navbar"

.container.grey.lighten-3.signup-box
  .row
    .col.s12.l12
      .row
        .col.s12.l12
          %h1.center-align Repertorios
        .col.s12.l12
          = link_to new_repertory_path, class: "btn btn-fb" do
            <i class="medium material-icons left">note_add</i>Nuevo Repertorio
      .row
        .col.s12.l12
          %table.table-v.striped.highlight.centered.responsive-table
            %thead
              %tr
                %th Usuario
                %th Hora de Ins.
                %th Fecha de Ins.
                %th N° de Repertorio
                %th N° que Corresponde
                %th Naturaleza del Documento
                %th Clase de Inscripción
                %th Registro Parcial
                %th Apellidos
                %th Nombres
                %th
                %th
                %th

            %tbody
              - @repertories.each do |repertory|
                %tr
                  %td= repertory.user.email
                  %td= repertory.time_repertory.strftime("%H:%M")
                  %td= repertory.date_repertory
                  %td= repertory.num_repertory
                  %td= repertory.num_inscription
                  %td= repertory.document
                  %td= repertory.inscription
                  %td= repertory.register
                  %td= repertory.last_name
                  %td= repertory.name
                  %td= link_to 'Ver', repertory
                  %td= link_to 'Editar', edit_repertory_path(repertory)
                  %td
                    = link_to repertory, :method => :delete, :data => { :confirm => 'Are you sure?' } do
                      <i class="small material-icons left">delete</i>

=render "layouts/footer"

app/views/repertories/new.html.haml
=render "layouts/navbar"
.container.grey.lighten-3
  .row
    .col.s12.l12
      .row
        .col.s12.l12
          %h4.center-align Nuevo Repertorio
      .row
        .col.s12.l12
          = render 'form'

=render "layouts/footer"

app/views/repertories/show.html.haml
=render "layouts/navbar"

.container.grey.lighten-3.signup-box
  .row
    .col.s12
      .row
        .col.s12.transform-uppercase.center-align
          %h5 Repertorio N°: #{@repertory.num_repertory}
      .row
        .col.s12.l12
          %table.table-v.bordered.highlight.centered.responsive-table
            %thead
              %tr
                %th Hora de Ins.
                %th Fecha de Ins.
                %th N° que Corresponde
                %th Naturaleza del Documento
                %th Clase de Inscripción
                %th Registro Parcial
                %th Apellidos
                %th Nombres
                %th
                %th
            %tbody
              %tr
                %td= @repertory.time_repertory.strftime("%H:%M")
                %td= @repertory.date_repertory
                %td= @repertory.num_inscription
                %td= @repertory.document
                %td= @repertory.inscription
                %td= @repertory.register
                %td= @repertory.last_name
                %td= @repertory.name
                %td= link_to "Editar", edit_repertory_path(@repertory)
                %td= link_to "Eliminar", @repertory, :method => :delete, :data => { :confirm => 'Are you sure?' }
  .row
    .col.s12
      %ul
        %li.col.s6
          = link_to "Regresar", repertories_path, class: "btn btn-ap"
        %li.col.s6
          = link_to 'Nuevo Repertorio', new_repertory_path, class: "btn btn-ap"

=render "layouts/footer"