config/routes.rb
Rails.application.routes.draw do
  
  resources :prohibitions
  resources :repertories
  resources :inscriptions do
    resources :appearers
  end

  resources :consultations


  devise_for :users
  authenticated :user do
    root 'welcome#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root "welcome#unregistered", as: :unregistered_root
    end
  end


end

app/models/prohibition.rb
class Prohibition < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user, :last_name, :name, :type_prohibition, :inscription, :date_inscription
end

app/controllers/prohibitions_controller.rb
class ProhibitionsController < ApplicationController
  before_action :set_prohibition, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /prohibitions
  # GET /prohibitions.json
  def index
    @prohibitions = Prohibition.all
  end

  # GET /prohibitions/1
  # GET /prohibitions/1.json
  def show
  end

  # GET /prohibitions/new
  def new
    @prohibition = Prohibition.new
  end

  # GET /prohibitions/1/edit
  def edit
  end

  # POST /prohibitions
  # POST /prohibitions.json
  def create
    @prohibition = current_user.prohibitions.new(prohibition_params)

    respond_to do |format|
      if @prohibition.save
        format.html { redirect_to @prohibition, notice: 'Prohibition was successfully created.' }
        format.json { render :show, status: :created, location: @prohibition }
      else
        format.html { render :new }
        format.json { render json: @prohibition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prohibitions/1
  # PATCH/PUT /prohibitions/1.json
  def update
    respond_to do |format|
      if @prohibition.update(prohibition_params)
        format.html { redirect_to @prohibition, notice: 'Prohibition was successfully updated.' }
        format.json { render :show, status: :ok, location: @prohibition }
      else
        format.html { render :edit }
        format.json { render json: @prohibition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prohibitions/1
  # DELETE /prohibitions/1.json
  def destroy
    @prohibition.destroy
    respond_to do |format|
      format.html { redirect_to prohibitions_url, notice: 'Prohibition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prohibition
      @prohibition = Prohibition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prohibition_params
      params.require(:prohibition).permit(:user_id, :last_name, :name, :type_prohibition, :inscription, :date_inscription)
    end
end

app/helpers/prohibitions_helper.rb
module ProhibitionsHelper
end

app/views/prohibitions/_form.html.haml
.container.signup-box
  .row
    .col.s12.l12
      = simple_form_for @prohibition do |f|
        -if @prohibition.errors.any?
          #error_explanation
            %h3.chip
              = "#{@prohibition.errors.count} errores encontrados:"
              <i class="material-icons">close</i>
            %ul
              -@prohibition.errors.full_messages.each do |msg|
                %li.chip.waves-effect.waves-light.btn-large
                  =msg
                  <i class="material-icons">close</i>
        .row
          .col.s12.l12
            .section
              .row
                .col.s12.l12
                  .input-field.col.s12.l12
                    =f.text_field :last_name
                    %label{for: "#{:last_name}", class: "active"} Apellidos
                  .input-field.col.s12.l12
                    =f.text_field :name
                    %label{for: "#{:name}", class: "active"} Nombres
                  .input-field.col.s12.l12
                    =f.text_field :type_prohibition
                    %label{for: "#{:type_prohibition}", class: "active"} Tipo de Acto
                  .input-field.col.s12.l12
                    =f.text_field :inscription
                    %label{for: "#{:inscription}", class: "active"} Número de Inscripción
                  .input-field.col.s12.l12
                    =f.text_field :date_inscription
                    %label{for: "#{:date_inscription}", class: "active"} Año de Inscripción
              .row
                .col.s12.l6
                  %button{class:"btn btn-fb", type:"submit", name:"action"}
                    Guardar<i class="material-icons right">send</i>
                .col.s12.l6
                  =link_to "Cancelar", prohibitions_path, class: "btn btn-fb"

app/views/prohibitions/edit.html.haml
=render "layouts/navbar"
.container.grey.lighten-3
  .row
    .col.s12.l12
      .row
        .col.s12.l12
          %h1.center-align Editar Inscripción
      .row
        .col.s12.l12
          = render 'form'

=render "layouts/footer"

app/views/prohibitions/index.html.haml
=render "layouts/navbar"

.container.grey.lighten-3.signup-box
  .row
    .col.s12.l12
      .row
        .col.s12.l12
          %h1.center-align Gravámenes y Prohibiciones
        .col.s12.l12
          = link_to new_prohibition_path, class: "btn btn-fb" do
            <i class="medium material-icons left">note_add</i>Nueva Inscripción
      .row
        .col.s6.l12
          %table.striped.highlight.centered.responsive-table
            %thead
              %tr
                %th Usuario
                %th Ń° Inscripción
                %th Año de Inscripción
                %th Tipo de Acto
                %th Apellidos
                %th Nombres
                %th
                %th
                %th

            %tbody
              - @prohibitions.each do |prohibition|
                %tr
                  %td= prohibition.user.email
                  %td= prohibition.inscription
                  %td= prohibition.date_inscription
                  %td= prohibition.type_prohibition
                  %td= prohibition.last_name
                  %td= prohibition.name
                  %td= link_to 'Ver', prohibition
                  %td= link_to 'Editar', edit_prohibition_path(prohibition)
                  %td
                    = link_to prohibition, :method => :delete, :data => { :confirm => 'Are you sure?' } do
                      <i class="small material-icons left">delete</i>

=render "layouts/footer"

app/views/prohibitions/new.html.haml
=render "layouts/navbar"
.container.grey.lighten-3
  .row
    .col.s12.l12
      .row
        .col.s12.l12
          %h1.center-align Nueva Inscripción
      .row
        .col.s12.l12
          = render 'form'

=render "layouts/footer"

app/views/prohibitions/show.html.haml
=render "layouts/navbar"

.container.grey.lighten-3.signup-box
  .row
    .col.s12
      .row
        .col.s12.transform-uppercase.center-align
          %h5 #{@prohibition.type_prohibition} N°: #{@prohibition.inscription}
      .row
        .col.s12.l12
          %table.table-v.bordered.highlight.centered.responsive-table
            %thead
              %tr
                %th N° de Ins.
                %th Fecha de Ins.
                %th Tipo de Acto
                %th Apellidos
                %th Nombres
                %th
                %th
            %tbody
              %tr
                %td= @prohibition.inscription
                %td= @prohibition.date_inscription
                %td= @prohibition.type_prohibition
                %td= @prohibition.last_name
                %td= @prohibition.name
                %td= link_to "Editar", edit_prohibition_path(@prohibition)
                %td= link_to "Eliminar", @prohibition, :method => :delete, :data => { :confirm => 'Are you sure?' }
  .row
    .col.s12
      %ul
        %li.col.s6
          = link_to "Regresar", prohibitions_path, class: "btn btn-ap"
        %li.col.s6
          = link_to 'Nuevo Repertorio', new_prohibition_path, class: "btn btn-ap"

=render "layouts/footer"