config/routes.rb
Rails.application.routes.draw do
  
  resources :prohibitions
  resources :repertories
  resources :inscriptions do
    resources :appearers
  end

  resources :consultations


  devise_for :users
  authenticated :user do
    root 'welcome#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root "welcome#unregistered", as: :unregistered_root
    end
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def unregistered
  	
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.haml
=render "layouts/navbar"

.container.grey.lighten-3
  .row
    .col.s12.l8.offset-l2
      .row
        .col.s12.l8.offset-l2
          %h1.center-align Bienvenidos
      .row
        .col.s4.l4
          .card.blue.lighten-5
            .card-content.blue-text.text-darken-2.center-align
              %span.card-title
                %i{class: "large material-icons"} recent_actors
              %h5 Indices
            .card-action.center-align.signup-box
              .row
                =link_to "Nuevo", new_inscription_path, class: "btn btn-fb"
              .row
                =link_to "Ver", inscriptions_path, class: "btn btn-fb"
        .col.s4.l4
          .card.blue.lighten-5
            .card-content.blue-text.text-darken-2.center-align
              %span.card-title
                %i{class: "large material-icons"} create_new_folder
              %h5 Repertorios
            .card-action.center-align.signup-box
              .row
                =link_to "Nuevo", new_repertory_path, class: "btn btn-fb"
              .row
                =link_to "Ver", repertories_path, class: "btn btn-fb"
        .col.s4.l4
          .card.blue.lighten-5
            .card-content.blue-text.text-darken-2.center-align
              %span.card-title
                %i{class: "large material-icons"} library_books
              %h5 Búsqueda
            .card-action.center-align.signup-box
              =link_to "Ver", consultations_path, class: "btn btn-fb"
      .row
        .col.s4.l4
          .card.blue.lighten-5
            .card-content.blue-text.text-darken-2.center-align
              %span.card-title
                %i{class: "large material-icons"} recent_actors
              %h5 Gravámenes y Prohibiciones
            .card-action.center-align.signup-box
              .row
                =link_to "Nuevo", new_prohibition_path, class: "btn btn-fb"
              .row
                =link_to "Ver", prohibitions_path, class: "btn btn-fb"

=render "layouts/footer"

app/views/welcome/unregistered.haml
=render "layouts/navbar"

%section#main-container
  .container
    .row
      .col.s10.push-s1
        .row
          .col.m5.hide-on-small-only
            = image_tag "logo.png", class: "logo"
          .col.s12.m7
            .row
              .signup-box
                %h1.platzigram Registro de la Propiedad y Mercantil del cantón La Troncal
                %h2 Sistema Índices
                %section
                  =link_to new_user_session_path, class: "btn btn-fb" do
                    <i class="medium material-icons left">perm_identity</i>Iniciar sesión

=render "layouts/footer"