config/routes.rb
Rails.application.routes.draw do
  
  resources :prohibitions
  resources :repertories
  resources :inscriptions do
    resources :appearers
  end

  resources :consultations


  devise_for :users
  authenticated :user do
    root 'welcome#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root "welcome#unregistered", as: :unregistered_root
    end
  end


end

app/models/inscription.rb
class Inscription < ActiveRecord::Base
  
  validates_presence_of :num_inscription, :act, :date_inscription, :user

  belongs_to :user
  has_many :appearers, dependent: :destroy

end

app/controllers/inscriptions_controller.rb
class InscriptionsController < ApplicationController
  before_action :set_inscription, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /inscriptions
  # GET /inscriptions.json
  def index
    @inscriptions = current_user.inscriptions
  end

  # GET /inscriptions/1
  # GET /inscriptions/1.json
  def show
    #@appearer = Appearer.new
  end

  # GET /inscriptions/new
  def new
    @inscription = Inscription.new
  end

  # GET /inscriptions/1/edit
  def edit
  end

  # POST /inscriptions
  # POST /inscriptions.json
  def create
    @inscription = current_user.inscriptions.new(inscription_params)

    respond_to do |format|
      if @inscription.save
        format.html { redirect_to @inscription, notice: 'Inscription was successfully created.' }
        format.json { render :show, status: :created, location: @inscription }
      else
        format.html { render :new }
        format.json { render json: @inscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inscriptions/1
  # PATCH/PUT /inscriptions/1.json
  def update
    respond_to do |format|
      if @inscription.update(inscription_params)
        format.html { redirect_to @inscription, notice: 'Inscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @inscription }
      else
        format.html { render :edit }
        format.json { render json: @inscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inscriptions/1
  # DELETE /inscriptions/1.json
  def destroy
    @inscription.destroy
    respond_to do |format|
      format.html { redirect_to inscriptions_url, notice: 'Inscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inscription
      @inscription = Inscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inscription_params
      params.require(:inscription).permit(:user_id, :num_inscription, :act, :date_inscription)
    end
end

app/helpers/inscriptions_helper.rb
module InscriptionsHelper
end

app/views/inscriptions/_form.html.haml
.container.signup-box
  .row
    .col.s12.l12
      = simple_form_for @inscription do |f|
        -if @inscription.errors.any?
          #error_explanation
            %h3.chip
              = "#{@inscription.errors.count} errores encontrados:"
              <i class="material-icons">close</i>
            %ul
              -@inscription.errors.full_messages.each do |msg|
                %li.chip.waves-effect.waves-light.btn-large
                  =msg
                  <i class="material-icons">close</i>
        .row
          .col.s12.l12
            .section
              .row
                .col.s12.l12
                  .input-field.col.s12.l12
                    =f.text_field :num_inscription
                    %label{for: "#{:num_inscription}", class: "active"} Número de Inscripción
                  .input-field.col.s12.l12
                    =f.text_field :act
                    %label{for: "#{:act}", class: "active"} Tipo de Acto o Contrato
                  .input-field.col.s12.l12
                    =f.text_field :date_inscription
                    %label{for: "#{:date_inscription}", class: "active"} Año de Inscripción
              .row
                .col.s12.l6
                  %button{class:"btn btn-fb", type:"submit", name:"action"}
                    Guardar<i class="material-icons right">send</i>
                .col.s12.l6
                  =link_to "Cancelar", inscriptions_path, class: "btn btn-fb"

app/views/inscriptions/edit.html.haml
%h1 Editing inscription

= render 'form'

= link_to 'Show', @inscription
\|
= link_to 'Back', inscriptions_path

app/views/inscriptions/index.html.haml
=render "layouts/navbar"

.container.grey.lighten-3.signup-box
  .row
    .col.s12.l12
      .row
        .col.s12.l12
          %h1.center-align Índices
        .col.s12.l12
          = link_to new_inscription_path, class: "btn btn-fb" do
            <i class="medium material-icons left">note_add</i>Nueva Inscripción
      .row
        .col.s6.l12
          %table.striped.highlight.centered.responsive-table
            %thead
              %tr
                %th Usuario
                %th Ń° Inscripción
                %th Año de Inscripción
                %th Tipo de Acto/Contrato
                %th
                %th
                %th

            %tbody
              - @inscriptions.each do |inscription|
                %tr
                  %td= inscription.user.email
                  %td= inscription.num_inscription
                  %td= inscription.date_inscription
                  %td= inscription.act
                  %td= link_to 'Ver', inscription
                  %td= link_to 'Editar', edit_inscription_path(inscription)
                  %td
                    = link_to inscription, :method => :delete, :data => { :confirm => 'Are you sure?' } do
                      <i class="small material-icons left">delete</i>

=render "layouts/footer"

app/views/inscriptions/new.html.haml
=render "layouts/navbar"
.container.grey.lighten-3
  .row
    .col.s12.l12
      .row
        .col.s12.l12
          %h1.center-align Nueva Inscripción
      .row
        .col.s12.l12
          = render 'form'

=render "layouts/footer"

app/views/inscriptions/show.html.haml
=render "layouts/navbar"

.container.grey.lighten-3.signup-box
  .row
    .col.s12
      .container
        .row
          .col.s12.transform-uppercase.center-align
            %h5 Inscripción
            %table.bordered.highlight.centered.responsive-table
              %thead
                %tr
                  %th Acto o Contrato
                  %th N° de Inscripción
                  %th Año de Inscripción
                  %th
                  %th
              %tbody
                %tr
                  %td= @inscription.act
                  %td= @inscription.num_inscription
                  %td= @inscription.date_inscription
                  %td= link_to "Editar", edit_inscription_path(@inscription)
                  %td= link_to "Eliminar", @inscription, :method => :delete, :data => { :confirm => 'Are you sure?' }

  .row
    .col.s12
      %ul
        %li.col.s6
          = link_to "Regresar", inscriptions_path, class: "btn btn-ap"
        %li.col.s6
          = link_to 'Nuevo Compareciente', new_inscription_appearer_path(@inscription), class: "btn btn-ap"
  .row
    .col.s12
      .container
        .row
          .col.s12.transform-uppercase.center-align
            %h5 Vendedores
            %table.table-v.bordered.highlight.centered.responsive-table
              %thead
                %tr
                  %th Apellidos
                  %th Nombres
                  %th Calidad
                  %th Tipo de Interviniente
                  %th Persona que Representa o Le Representa
                  %th
                  %th

              %tbody
                -@inscription.appearers.each do |appearer|
                  -if(appearer.type_appearer == "VENDEDOR")
                    %tr
                      %td= appearer.last_name
                      %td= appearer.name
                      %td= appearer.type_appearer
                      %td= appearer.type_representative
                      %td= appearer.representative
                      %td= link_to 'Editar', edit_inscription_appearer_path(@inscription, appearer.id)
                      %td= link_to 'Eliminar', inscription_appearer_path(@inscription, appearer.id), :method => :delete, :data => { :confirm => 'Are you sure?' }

  .row
    .col.s12
      .container
        .row
          .col.s12.transform-uppercase.center-align
            %h5 Compradores
            %table.table-v.bordered.highlight.centered.responsive-table
              %thead
                %tr
                  %th Apellidos
                  %th Nombres
                  %th Calidad
                  %th Tipo de Interviniente
                  %th Persona que Representa o Le Representa
                  %th
                  %th

              %tbody
                -@inscription.appearers.each do |appearer|
                  -if(appearer.type_appearer == "COMPRADOR")
                    %tr
                      %td= appearer.last_name
                      %td= appearer.name
                      %td= appearer.type_appearer
                      %td= appearer.type_representative
                      %td= appearer.representative
                      %td= link_to 'Editar', edit_inscription_appearer_path(@inscription, appearer.id)
                      %td= link_to 'Eliminar', inscription_appearer_path(@inscription, appearer.id), :method => :delete, :data => { :confirm => 'Are you sure?' }
=render "layouts/footer"